import { FiBookOpen, FiMail, FiMessageSquare, FiSend } from 'react-icons/fi'
import PageHero from '../components/marketing/PageHero'
import Reveal from '../components/ui/Reveal'
import { images } from '../data/publicContent'

export default function Contact(){return <>
 <PageHero eyebrow="Contact" title="Let’s talk about better bug triage." text="Have a project question, integration idea, or want to understand how BugNerve fits into an engineering workflow? Send us a message." image={images.contact} imageAlt="Modern software office" primary={['View documentation','/docs']} secondary={['Start free','/register']} />
 <section className="section contact-page"><div className="container contact-page__grid"><Reveal direction="left"><div className="contact-copy"><span className="eyebrow"><span className="eyebrow__dot"/>Get in touch</span><h2>Product questions, technical conversations, and project inquiries.</h2><p>Use the form or choose the channel that fits your question.</p><div className="contact-methods"><a href="mailto:hello@bugnerve.dev"><FiMail/><div><strong>General</strong><span>hello@bugnerve.dev</span></div></a><a href="mailto:support@bugnerve.dev"><FiMessageSquare/><div><strong>Support</strong><span>support@bugnerve.dev</span></div></a><a href="/docs"><FiBookOpen/><div><strong>Documentation</strong><span>Technical product overview</span></div></a></div></div></Reveal><Reveal direction="right"><form className="contact-form" onSubmit={e=>e.preventDefault()}><div className="form-grid"><label><span>Name</span><input placeholder="Your name"/></label><label><span>Email</span><input type="email" placeholder="you@example.com"/></label><label><span>Company / University</span><input placeholder="Organization"/></label><label><span>Role</span><select defaultValue=""><option value="" disabled>Select role</option><option>Team Leader</option><option>Developer</option><option>Tester</option><option>Student / Researcher</option></select></label></div><label><span>Subject</span><input placeholder="What would you like to discuss?"/></label><label><span>Message</span><textarea rows="7" placeholder="Tell us a little more…"/></label><button className="btn btn--primary" type="submit"><span>Send message</span><FiSend/></button></form></Reveal></div></section>
 </>}
