import { FiBarChart2, FiClock, FiTarget, FiTrendingDown, FiUsers, FiZap } from 'react-icons/fi'
import RolePageShell from '../../layout/RolePageShell'
import PageHeader from '../../components/PageHeader'
import StatCard from '../../components/StatCard'

export default function AnalyticsAppPage({ role, theme, onToggleTheme }) {
  const guide={title:'Analytics',purpose:'Analytics summarizes bug flow, team load and AI behavior. It is descriptive reporting; the Team Leader still makes operational decisions.',role:role==='admin'?'Admin / Owner':'Team Leader',actions:['Filter by project and date','Review resolution and triage trends','Inspect AI acceptance and workload distribution'],api:['GET /api/analytics/overview','GET /api/analytics/bugs','GET /api/analytics/ai','GET /api/analytics/developers']}
  return <RolePageShell role={role} theme={theme} onToggleTheme={onToggleTheme} guide={guide}><PageHeader eyebrow="Reporting" title="Analytics" description="See whether triage is getting faster, whether workload is balanced and how often people agree with AI recommendations."/><div className="stat-strip"><StatCard label="Avg. triage time" value="7m 42s" note="18% faster vs last month" icon={FiClock}/><StatCard label="Avg. resolution" value="1.8d" note="Across closed bugs" icon={FiTrendingDown} tone="green"/><StatCard label="AI acceptance" value="87%" note="Human review decisions" icon={FiTarget} tone="purple"/><StatCard label="Active developers" value="11" note="3 currently below average load" icon={FiUsers} tone="orange"/></div><div className="analytics-grid"><section className="app-panel analytics-card"><div className="page-panel__head"><div><span>Bug pressure</span><h3>Open bugs by week</h3></div><FiBarChart2/></div><div className="big-chart-bars">{[34,48,42,61,56,69,63,52,44,39,46,41].map((height,index)=><i key={index} style={{height:`${height}%`}}/>)}</div></section><section className="app-panel analytics-card"><div className="page-panel__head"><div><span>AI behavior</span><h3>Human decisions</h3></div><FiZap/></div><div className="donut-wrap"><div className="fake-donut"><span>87%<small>accepted</small></span></div><ul><li><i className="green"/>Accepted <b>87%</b></li><li><i className="orange"/>Modified <b>9%</b></li><li><i className="red"/>Rejected <b>4%</b></li></ul></div></section><section className="app-panel analytics-card analytics-card--wide"><div className="page-panel__head"><div><span>Components</span><h3>Where bugs are concentrating</h3></div></div><div className="component-bars">{[['Authentication',82],['Payments',68],['Frontend',57],['Search',44],['Notifications',36]].map(([name,value])=><div key={name}><span>{name}</span><i><em style={{width:`${value}%`}}/></i><b>{value}</b></div>)}</div></section></div></RolePageShell>
}
