import { useState } from 'react'
import { FiMail, FiPlus, FiUserCheck, FiUsers } from 'react-icons/fi'
import RolePageShell from '../../layout/RolePageShell'
import PageHeader from '../../components/PageHeader'
import DataTable from '../../components/DataTable'
import StatusPill from '../../components/StatusPill'
import Modal from '../../components/Modal'
import { members } from '../../data/mockData'

export default function TeamPage({ role, theme, onToggleTheme }) {
  const [inviteOpen,setInviteOpen]=useState(false)
  const guide={title:'Team',purpose:role==='admin'?'Workspace admins manage membership and workspace/project access here.':'Team Leaders inspect workload and expertise before assigning bugs; they do not manage billing or workspace ownership here.',role:role==='admin'?'Admin / Owner':'Team Leader',actions:role==='admin'?['Invite a member','Set project role','Deactivate access','Inspect connected identity']:['Review developer workload','Compare expertise','Open a developer profile'],api:role==='admin'?['GET /api/workspaces/{id}/members','POST /api/workspaces/{id}/invitations','PATCH /api/projects/{id}/members/{memberId}']:['GET /api/projects/{id}/members','GET /api/developers/{id}/stats']}
  const columns=[{key:'name',label:'Member',render:(row)=><div className="member-cell"><span>{row.name.split(' ').map(x=>x[0]).join('').slice(0,2)}</span><div><b>{row.name}</b><small>{row.email}</small></div></div>},{key:'role',label:'Project role',render:(row)=><StatusPill tone={row.role==='Team Leader'?'purple':row.role==='Tester'?'blue':'green'}>{row.role}</StatusPill>},{key:'bugs',label:'Active bugs'},{key:'resolved',label:'Resolved'},{key:'status',label:'Status',render:(row)=><StatusPill tone={row.status==='Active'?'green':'orange'}>{row.status}</StatusPill>}]
  return <RolePageShell role={role} theme={theme} onToggleTheme={onToggleTheme} guide={guide}><PageHeader eyebrow={role==='admin'?'Access & membership':'Capacity & expertise'} title="Team" description={role==='admin'?'Invite people, assign project roles and keep workspace access clear.':'See who has the right context and enough capacity before making an assignment.'} action={role==='admin'?'Invite member':null} actionIcon={FiPlus} onAction={()=>setInviteOpen(true)}/><div className="stat-strip"><article className="stat-card"><span className="stat-card__icon"><FiUsers/></span><div><small>Members</small><b>84</b><p>Across the workspace</p></div></article><article className="stat-card stat-card--green"><span className="stat-card__icon"><FiUserCheck/></span><div><small>Available now</small><b>11</b><p>Developers below load threshold</p></div></article><article className="stat-card stat-card--purple"><span className="stat-card__icon"><FiMail/></span><div><small>Pending invites</small><b>6</b><p>Awaiting acceptance</p></div></article></div><section className="app-panel page-panel"><div className="page-panel__head"><div><span>BugNerve Core</span><h3>Project members</h3></div></div><DataTable columns={columns} rows={members}/></section><Modal open={inviteOpen} onClose={()=>setInviteOpen(false)} eyebrow="Workspace invitation" title="Invite a teammate" size="md"><div className="simple-form"><label>Email<input placeholder="name@company.com"/></label><label>Project role<select><option>Developer</option><option>Tester</option><option>Team Leader</option></select></label><p className="form-help">The invite assigns a project role. Workspace Owner/Admin remains a separate permission.</p><div className="modal-actions"><button className="secondary" onClick={()=>setInviteOpen(false)}>Cancel</button><button className="primary" onClick={()=>setInviteOpen(false)}><FiMail/> Send invitation</button></div></div></Modal></RolePageShell>
}
