import { useState } from 'react'
import { FiCheck, FiCheckCircle, FiGitCommit, FiRefreshCw, FiX } from 'react-icons/fi'
import RolePageShell from '../../layout/RolePageShell'
import PageHeader from '../../components/PageHeader'
import StatusPill from '../../components/StatusPill'
import Modal from '../../components/Modal'
import { verificationRows } from '../../data/mockData'

export default function VerificationPage({theme,onToggleTheme}){const [selected,setSelected]=useState(null);const [result,setResult]=useState(null);const guide={title:'Verification',purpose:'A bug is not finished just because a developer marks it resolved. The Tester verifies the fix and either closes the loop or reopens the issue.',role:'Tester',actions:['Open resolved bug','Review developer resolution and linked commit','Pass and verify','Fail and reopen with a reason'],api:['GET /api/bugs?status=RESOLVED&verification=pending','POST /api/bugs/{id}/verification','PATCH /api/bugs/{id}/status']};return <RolePageShell role="tester" theme={theme} onToggleTheme={onToggleTheme} guide={guide}><PageHeader eyebrow="Final quality gate" title="Verification" description="Re-test resolved bugs against the original report before they are closed."/><div className="verification-page-list">{verificationRows.map(item=><article className="app-panel verify-card" key={item.id}><span className="verify-card__icon"><FiCheckCircle/></span><div><small>{item.id}</small><h3>{item.title}</h3><p>Resolved {item.resolved} by {item.developer}</p></div><div className="verify-card__meta"><StatusPill tone="orange">{item.priority}</StatusPill><span><FiGitCommit/> {item.commit}</span></div><button className="primary compact" onClick={()=>{setSelected(item);setResult(null)}}>Verify fix</button></article>)}</div>{selected&&<Modal open onClose={()=>setSelected(null)} eyebrow="Tester verification" title={`${selected.id} · ${selected.title}`} size="lg"><div className="verification-modal"><div className="resolved-summary"><FiGitCommit/><div><small>Developer resolution</small><b>{selected.developer} linked commit {selected.commit}</b><p>Session refresh handling was updated and the previous failure path was covered with a regression test.</p></div></div><div className="verify-checks"><label><input type="checkbox"/> Original steps no longer reproduce the issue</label><label><input type="checkbox"/> Expected result is now correct</label><label><input type="checkbox"/> No obvious regression found</label></div><div className="verify-decision"><button className={result==='pass'?'pass active':'pass'} onClick={()=>setResult('pass')}><FiCheck/> Pass</button><button className={result==='fail'?'fail active':'fail'} onClick={()=>setResult('fail')}><FiX/> Fail / Reopen</button></div>{result==='fail'&&<textarea className="reopen-note" placeholder="Why should this bug be reopened?" rows="3"/>}<div className="modal-actions"><button className="secondary" onClick={()=>setSelected(null)}>Cancel</button><button className="primary" disabled={!result} onClick={()=>setSelected(null)}>{result==='fail'?<><FiRefreshCw/> Reopen bug</>:<><FiCheckCircle/> Verify & close</>}</button></div></div></Modal>}</RolePageShell>}
