import { useState } from 'react'
import { FiCheck, FiFilter, FiSliders, FiUserCheck, FiX, FiZap } from 'react-icons/fi'
import RolePageShell from '../../layout/RolePageShell'
import PageHeader from '../../components/PageHeader'
import StatusPill from '../../components/StatusPill'
import Modal from '../../components/Modal'
import { triageQueue } from '../../data/mockData'

function ReviewModal({item,onClose}){const [decision,setDecision]=useState('accept');const [developer,setDeveloper]=useState(item.developer);return <Modal open onClose={onClose} eyebrow="Human-in-the-loop review" title={`${item.id} · ${item.title}`} size="xl"><div className="triage-review-demo triage-review-demo--queue"><section><span className="modal-kicker">Original report</span><h3>{item.title}</h3><p>The tester submitted the issue with reproduction steps, environment information and evidence. The report is already saved even if AI becomes unavailable.</p><div className="bug-evidence"><b>Reported context</b><span>Web application · Production</span><span>Chrome / Windows 11</span><span>Evidence: screenshot + log</span></div></section><section className="ai-review-column"><span className="modal-kicker">AI recommendation</span>{[['Severity',item.severity,`${item.confidence}%`],['Priority',item.priority,'86%'],['Component',item.component,'91%'],['Possible duplicate',`${item.duplicate}% match`,`${item.duplicate}%`]].map(row=><div className="ai-review-row" key={row[0]}><span>{row[0]}</span><b>{row[1]}</b><strong>{row[2]}</strong><i><em style={{width:row[2]}}/></i></div>)}<div className="developer-reason"><span>{item.developerScore}%</span><div><b>{item.developer}</b><p>Top developer candidate from expertise, similar fixes, file history and workload.</p></div></div></section><section><span className="modal-kicker">Your decision</span><div className="decision-buttons">{[['accept',FiCheck],['modify',FiSliders],['reject',FiX]].map(([key,Icon])=><button className={decision===key?'is-active':''} key={key} onClick={()=>setDecision(key)}><Icon/>{key[0].toUpperCase()+key.slice(1)}</button>)}</div><label>Final developer<select value={developer} onChange={(e)=>setDeveloper(e.target.value)}><option>{item.developer}</option><option>Ahmed Hassan</option><option>Sara Omar</option><option>Youssef Nader</option></select></label><p className="form-help">Accept keeps AI suggestions, Modify lets you override them, and Reject discards the AI recommendation while the bug stays in the tracker.</p></section></div><div className="modal-actions"><button className="secondary" onClick={onClose}>Review later</button><button className="primary" onClick={onClose}><FiUserCheck/> Save final decision</button></div></Modal>}

export default function AITriageQueuePage({theme,onToggleTheme}){const [selected,setSelected]=useState(null);const guide={title:'AI Triage',purpose:'This is the signature Team Leader workspace. AI prepares a first pass, then a human accepts, modifies or rejects before final assignment.',role:'Team Leader',actions:['Prioritize pending reviews','Inspect confidence and duplicate signals','Review developer recommendation','Accept, modify or reject'],api:['GET /api/triage/queue','GET /api/bugs/{id}/ai-analysis','POST /api/bugs/{id}/triage-review','GET /api/bugs/{id}/recommendations']};return <RolePageShell role="leader" theme={theme} onToggleTheme={onToggleTheme} guide={guide}><PageHeader eyebrow="Human-in-the-loop" title="AI Triage" description="AI handles the first pass. You review the evidence and make the final triage and assignment decision."/><section className="page-toolbar"><button><FiFilter/> Confidence</button><select><option>All severities</option><option>Critical</option><option>Major</option><option>Normal</option></select><select><option>Awaiting review</option><option>Reviewed</option></select></section><div className="triage-queue-grid">{triageQueue.map(item=><article className="triage-queue-card" key={item.id}><header><div><small>{item.id}</small><h3>{item.title}</h3></div><StatusPill tone={item.confidence<80?'orange':'purple'}>{item.confidence}% confidence</StatusPill></header><div className="triage-predictions"><span><small>Severity</small><b>{item.severity}</b></span><span><small>Priority</small><b>{item.priority}</b></span><span><small>Component</small><b>{item.component}</b></span><span><small>Duplicate</small><b>{item.duplicate}%</b></span></div><div className="triage-developer"><FiUserCheck/><div><small>Best-fit developer</small><b>{item.developer}</b></div><strong>{item.developerScore}%</strong></div><footer><span><FiZap/> Waiting for human review</span><button className="primary compact" onClick={()=>setSelected(item)}>Review</button></footer></article>)}</div>{selected&&<ReviewModal item={selected} onClose={()=>setSelected(null)}/>}</RolePageShell>}
